### PR TITLE
1.14

### PR DESCRIPTION
**Pull request by boy0001**
I need to fix the build script for jenkins so it fetches a 1.14 spigot jar. Will finish this / merge later. Also lighting needs work.

### CODE REVIEW

**Comment by yannicklamprecht** [comment]
Which WorldGuard version is targeted?

**Comment by mibby** [comment]
Would it be possible to target a newer WorldGuard build for the 1.14 FAWE release? WorldGuard 7.0.0 Beta 3 is over 6 months old at this point with 7.0.0 stable and 7.0.1 Beta 1 already superseding it. The last functional WorldGuard dev build for FAWE 1.14 (build 8) seems to be dev 1847, which is over 3 months old. 

I have a few things that are already requiring the newer WorldGuard builds due to deprecation and changes in 1.14 and WorldEdit. :(

**Comment by MattBDev** [comment]
@mibby Targeting the newest version of WorldGuard needs to be done seperately from 1.14 for the time being

**Comment by mibby** [comment]
@MattBDev Due to the command changes I presume? 

Also ran across some simple errors with quick testing of FAWE 1.14.

FAWE 1.14 dev 8
Paper dev 639 (Spigot 1.14.3)
WorldGuard dev 1847

Default generated FAWE config.
```
[11:38:29] [Server thread/INFO]: mibby issued server command: //wand
[11:38:42] [Server thread/INFO]: mibby issued server command: //cut
[11:38:42] [Craft Scheduler Thread - 7/WARN]: com.sk89q.worldedit.regions.CuboidRegion$2$1: End of iterator
[11:38:49] [Server thread/INFO]: mibby issued server command: //undo
[11:39:16] [Server thread/INFO]: mibby issued server command: //cut
[11:39:16] [Craft Scheduler Thread - 6/WARN]: com.sk89q.worldedit.regions.CuboidRegion$2$1: End of iterator
[11:39:24] [Server thread/INFO]: mibby issued server command: //undo
[11:39:36] [Server thread/INFO]: mibby issued server command: //cut
[11:39:36] [Craft Scheduler Thread - 5/WARN]: com.sk89q.worldedit.regions.CuboidRegion$2$1: End of iterator
[11:39:53] [Server thread/INFO]: mibby issued server command: //undo
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: java.lang.IllegalStateException: Asynchronous entity add!
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.addEntity0(WorldServer.java:956)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at net.minecraft.server.v1_14_R1.WorldServer.addEntity(WorldServer.java:893)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at com.boydti.fawe.bukkit.v1_14.BukkitChunk_1_14.call(BukkitChunk_1_14.java:441)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at com.boydti.fawe.bukkit.v1_14.BukkitChunk_1_14.call(BukkitChunk_1_14.java:70)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.run(ForkJoinTask.java:1434)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[11:39:53] [ForkJoinPool-5-worker-7/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Pull request closed without merging**
